//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.239.
// 
#pragma warning disable 1591

namespace RacingEventsTrackSystem.hardcardserver {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SyncServiceSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RelatedEnd))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(StructuralObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Competitor[]))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityKeyMember[]))]
    public partial class SyncService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SynchronizeCompetitorDataWithClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynchronizeEventsDataWithClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynchronizeRaceClassesDataWithClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynchronizeEventClassesDataWithClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynchronizeSessionsDataWithClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback SynchronizePassingsDataWithClientOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetCompetitorDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastPassingDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SyncService() {
            this.Url = global::RacingEventsTrackSystem.Properties.Settings.Default.RacingEventsTrackSystem_hardcardserver_SyncService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SynchronizeCompetitorDataWithClientCompletedEventHandler SynchronizeCompetitorDataWithClientCompleted;
        
        /// <remarks/>
        public event SynchronizeEventsDataWithClientCompletedEventHandler SynchronizeEventsDataWithClientCompleted;
        
        /// <remarks/>
        public event SynchronizeRaceClassesDataWithClientCompletedEventHandler SynchronizeRaceClassesDataWithClientCompleted;
        
        /// <remarks/>
        public event SynchronizeEventClassesDataWithClientCompletedEventHandler SynchronizeEventClassesDataWithClientCompleted;
        
        /// <remarks/>
        public event SynchronizeSessionsDataWithClientCompletedEventHandler SynchronizeSessionsDataWithClientCompleted;
        
        /// <remarks/>
        public event SynchronizePassingsDataWithClientCompletedEventHandler SynchronizePassingsDataWithClientCompleted;
        
        /// <remarks/>
        public event GetCompetitorDataCompletedEventHandler GetCompetitorDataCompleted;
        
        /// <remarks/>
        public event GetLastPassingDataCompletedEventHandler GetLastPassingDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchronizeCompetitorDataWithClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynchronizeCompetitorDataWithClient(System.DateTime lastSync, Competitor[] crinlist, out Competitor[] croutlist) {
            object[] results = this.Invoke("SynchronizeCompetitorDataWithClient", new object[] {
                        lastSync,
                        crinlist});
            croutlist = ((Competitor[])(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynchronizeCompetitorDataWithClientAsync(System.DateTime lastSync, Competitor[] crinlist) {
            this.SynchronizeCompetitorDataWithClientAsync(lastSync, crinlist, null);
        }
        
        /// <remarks/>
        public void SynchronizeCompetitorDataWithClientAsync(System.DateTime lastSync, Competitor[] crinlist, object userState) {
            if ((this.SynchronizeCompetitorDataWithClientOperationCompleted == null)) {
                this.SynchronizeCompetitorDataWithClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchronizeCompetitorDataWithClientOperationCompleted);
            }
            this.InvokeAsync("SynchronizeCompetitorDataWithClient", new object[] {
                        lastSync,
                        crinlist}, this.SynchronizeCompetitorDataWithClientOperationCompleted, userState);
        }
        
        private void OnSynchronizeCompetitorDataWithClientOperationCompleted(object arg) {
            if ((this.SynchronizeCompetitorDataWithClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynchronizeCompetitorDataWithClientCompleted(this, new SynchronizeCompetitorDataWithClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchronizeEventsDataWithClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynchronizeEventsDataWithClient(System.DateTime lastSync, Event[] eventslist) {
            object[] results = this.Invoke("SynchronizeEventsDataWithClient", new object[] {
                        lastSync,
                        eventslist});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynchronizeEventsDataWithClientAsync(System.DateTime lastSync, Event[] eventslist) {
            this.SynchronizeEventsDataWithClientAsync(lastSync, eventslist, null);
        }
        
        /// <remarks/>
        public void SynchronizeEventsDataWithClientAsync(System.DateTime lastSync, Event[] eventslist, object userState) {
            if ((this.SynchronizeEventsDataWithClientOperationCompleted == null)) {
                this.SynchronizeEventsDataWithClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchronizeEventsDataWithClientOperationCompleted);
            }
            this.InvokeAsync("SynchronizeEventsDataWithClient", new object[] {
                        lastSync,
                        eventslist}, this.SynchronizeEventsDataWithClientOperationCompleted, userState);
        }
        
        private void OnSynchronizeEventsDataWithClientOperationCompleted(object arg) {
            if ((this.SynchronizeEventsDataWithClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynchronizeEventsDataWithClientCompleted(this, new SynchronizeEventsDataWithClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchronizeRaceClassesDataWithClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynchronizeRaceClassesDataWithClient(System.DateTime lastSync, RaceClass[] raceclasseslist) {
            object[] results = this.Invoke("SynchronizeRaceClassesDataWithClient", new object[] {
                        lastSync,
                        raceclasseslist});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynchronizeRaceClassesDataWithClientAsync(System.DateTime lastSync, RaceClass[] raceclasseslist) {
            this.SynchronizeRaceClassesDataWithClientAsync(lastSync, raceclasseslist, null);
        }
        
        /// <remarks/>
        public void SynchronizeRaceClassesDataWithClientAsync(System.DateTime lastSync, RaceClass[] raceclasseslist, object userState) {
            if ((this.SynchronizeRaceClassesDataWithClientOperationCompleted == null)) {
                this.SynchronizeRaceClassesDataWithClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchronizeRaceClassesDataWithClientOperationCompleted);
            }
            this.InvokeAsync("SynchronizeRaceClassesDataWithClient", new object[] {
                        lastSync,
                        raceclasseslist}, this.SynchronizeRaceClassesDataWithClientOperationCompleted, userState);
        }
        
        private void OnSynchronizeRaceClassesDataWithClientOperationCompleted(object arg) {
            if ((this.SynchronizeRaceClassesDataWithClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynchronizeRaceClassesDataWithClientCompleted(this, new SynchronizeRaceClassesDataWithClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchronizeEventClassesDataWithClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynchronizeEventClassesDataWithClient(System.DateTime lastSync, EventClass[] eventclasseslist) {
            object[] results = this.Invoke("SynchronizeEventClassesDataWithClient", new object[] {
                        lastSync,
                        eventclasseslist});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynchronizeEventClassesDataWithClientAsync(System.DateTime lastSync, EventClass[] eventclasseslist) {
            this.SynchronizeEventClassesDataWithClientAsync(lastSync, eventclasseslist, null);
        }
        
        /// <remarks/>
        public void SynchronizeEventClassesDataWithClientAsync(System.DateTime lastSync, EventClass[] eventclasseslist, object userState) {
            if ((this.SynchronizeEventClassesDataWithClientOperationCompleted == null)) {
                this.SynchronizeEventClassesDataWithClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchronizeEventClassesDataWithClientOperationCompleted);
            }
            this.InvokeAsync("SynchronizeEventClassesDataWithClient", new object[] {
                        lastSync,
                        eventclasseslist}, this.SynchronizeEventClassesDataWithClientOperationCompleted, userState);
        }
        
        private void OnSynchronizeEventClassesDataWithClientOperationCompleted(object arg) {
            if ((this.SynchronizeEventClassesDataWithClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynchronizeEventClassesDataWithClientCompleted(this, new SynchronizeEventClassesDataWithClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchronizeSessionsDataWithClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynchronizeSessionsDataWithClient(System.DateTime lastSync, Session[] sessionslist) {
            object[] results = this.Invoke("SynchronizeSessionsDataWithClient", new object[] {
                        lastSync,
                        sessionslist});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynchronizeSessionsDataWithClientAsync(System.DateTime lastSync, Session[] sessionslist) {
            this.SynchronizeSessionsDataWithClientAsync(lastSync, sessionslist, null);
        }
        
        /// <remarks/>
        public void SynchronizeSessionsDataWithClientAsync(System.DateTime lastSync, Session[] sessionslist, object userState) {
            if ((this.SynchronizeSessionsDataWithClientOperationCompleted == null)) {
                this.SynchronizeSessionsDataWithClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchronizeSessionsDataWithClientOperationCompleted);
            }
            this.InvokeAsync("SynchronizeSessionsDataWithClient", new object[] {
                        lastSync,
                        sessionslist}, this.SynchronizeSessionsDataWithClientOperationCompleted, userState);
        }
        
        private void OnSynchronizeSessionsDataWithClientOperationCompleted(object arg) {
            if ((this.SynchronizeSessionsDataWithClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynchronizeSessionsDataWithClientCompleted(this, new SynchronizeSessionsDataWithClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SynchronizePassingsDataWithClient", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool SynchronizePassingsDataWithClient(System.DateTime lastSync, Passing[] passingslist) {
            object[] results = this.Invoke("SynchronizePassingsDataWithClient", new object[] {
                        lastSync,
                        passingslist});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void SynchronizePassingsDataWithClientAsync(System.DateTime lastSync, Passing[] passingslist) {
            this.SynchronizePassingsDataWithClientAsync(lastSync, passingslist, null);
        }
        
        /// <remarks/>
        public void SynchronizePassingsDataWithClientAsync(System.DateTime lastSync, Passing[] passingslist, object userState) {
            if ((this.SynchronizePassingsDataWithClientOperationCompleted == null)) {
                this.SynchronizePassingsDataWithClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSynchronizePassingsDataWithClientOperationCompleted);
            }
            this.InvokeAsync("SynchronizePassingsDataWithClient", new object[] {
                        lastSync,
                        passingslist}, this.SynchronizePassingsDataWithClientOperationCompleted, userState);
        }
        
        private void OnSynchronizePassingsDataWithClientOperationCompleted(object arg) {
            if ((this.SynchronizePassingsDataWithClientCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SynchronizePassingsDataWithClientCompleted(this, new SynchronizePassingsDataWithClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetCompetitorData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Competitor[] GetCompetitorData() {
            object[] results = this.Invoke("GetCompetitorData", new object[0]);
            return ((Competitor[])(results[0]));
        }
        
        /// <remarks/>
        public void GetCompetitorDataAsync() {
            this.GetCompetitorDataAsync(null);
        }
        
        /// <remarks/>
        public void GetCompetitorDataAsync(object userState) {
            if ((this.GetCompetitorDataOperationCompleted == null)) {
                this.GetCompetitorDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetCompetitorDataOperationCompleted);
            }
            this.InvokeAsync("GetCompetitorData", new object[0], this.GetCompetitorDataOperationCompleted, userState);
        }
        
        private void OnGetCompetitorDataOperationCompleted(object arg) {
            if ((this.GetCompetitorDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetCompetitorDataCompleted(this, new GetCompetitorDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetLastPassingData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Passing[] GetLastPassingData() {
            object[] results = this.Invoke("GetLastPassingData", new object[0]);
            return ((Passing[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLastPassingDataAsync() {
            this.GetLastPassingDataAsync(null);
        }
        
        /// <remarks/>
        public void GetLastPassingDataAsync(object userState) {
            if ((this.GetLastPassingDataOperationCompleted == null)) {
                this.GetLastPassingDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastPassingDataOperationCompleted);
            }
            this.InvokeAsync("GetLastPassingData", new object[0], this.GetLastPassingDataOperationCompleted, userState);
        }
        
        private void OnGetLastPassingDataOperationCompleted(object arg) {
            if ((this.GetLastPassingDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastPassingDataCompleted(this, new GetLastPassingDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Competitor : EntityObject {
        
        private long competitorIDField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private System.DateTime dOBField;
        
        private string genderField;
        
        private string vehicleTypeField;
        
        private string vehicleModelField;
        
        private System.Nullable<int> vehicleCCField;
        
        private System.Nullable<long> classIDField;
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string cityField;
        
        private string stateField;
        
        private string postalCodeField;
        
        private string countryField;
        
        private string phoneField;
        
        private bool deletedField;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        private EntityReferenceOfRaceClass raceClassReferenceField;
        
        /// <remarks/>
        public long CompetitorID {
            get {
                return this.competitorIDField;
            }
            set {
                this.competitorIDField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DOB {
            get {
                return this.dOBField;
            }
            set {
                this.dOBField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleModel {
            get {
                return this.vehicleModelField;
            }
            set {
                this.vehicleModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> VehicleCC {
            get {
                return this.vehicleCCField;
            }
            set {
                this.vehicleCCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine1 {
            get {
                return this.addressLine1Field;
            }
            set {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine2 {
            get {
                return this.addressLine2Field;
            }
            set {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        public string AddressLine3 {
            get {
                return this.addressLine3Field;
            }
            set {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        public string State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        public string Country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        public bool Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfRaceClass RaceClassReference {
            get {
                return this.raceClassReferenceField;
            }
            set {
                this.raceClassReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfRaceClass : EntityReference {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfValidTag))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfSession))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfRaceClass))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityReference : RelatedEnd {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKey {
        
        private string entitySetNameField;
        
        private string entityContainerNameField;
        
        private EntityKeyMember[] entityKeyValuesField;
        
        /// <remarks/>
        public string EntitySetName {
            get {
                return this.entitySetNameField;
            }
            set {
                this.entitySetNameField = value;
            }
        }
        
        /// <remarks/>
        public string EntityContainerName {
            get {
                return this.entityContainerNameField;
            }
            set {
                this.entityContainerNameField = value;
            }
        }
        
        /// <remarks/>
        public EntityKeyMember[] EntityKeyValues {
            get {
                return this.entityKeyValuesField;
            }
            set {
                this.entityKeyValuesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityKeyMember {
        
        private string keyField;
        
        private object valueField;
        
        /// <remarks/>
        public string Key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        public object Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReference))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfValidTag))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfSession))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfEvent))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityReferenceOfRaceClass))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class RelatedEnd {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EntityObject))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Passing))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Session))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RaceClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Competitor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class StructuralObject {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Passing))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Session))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(EventClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RaceClass))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Event))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Competitor))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class EntityObject : StructuralObject {
        
        private EntityKey entityKeyField;
        
        /// <remarks/>
        public EntityKey EntityKey {
            get {
                return this.entityKeyField;
            }
            set {
                this.entityKeyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Passing : EntityObject {
        
        private long passingIDField;
        
        private long sessionIDField;
        
        private long rFIDField;
        
        private System.DateTime passngTimeField;
        
        private long raceTimeField;
        
        private System.Nullable<long> lapTimeField;
        
        private System.Nullable<short> lapField;
        
        private System.Nullable<short> leaderLapField;
        
        private System.Nullable<byte> flagStateField;
        
        private System.Nullable<bool> deletedField;
        
        private System.Nullable<bool> invalidField;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        private EntityReferenceOfSession sessionReferenceField;
        
        private EntityReferenceOfValidTag validTagReferenceField;
        
        /// <remarks/>
        public long PassingID {
            get {
                return this.passingIDField;
            }
            set {
                this.passingIDField = value;
            }
        }
        
        /// <remarks/>
        public long SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public long RFID {
            get {
                return this.rFIDField;
            }
            set {
                this.rFIDField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime PassngTime {
            get {
                return this.passngTimeField;
            }
            set {
                this.passngTimeField = value;
            }
        }
        
        /// <remarks/>
        public long RaceTime {
            get {
                return this.raceTimeField;
            }
            set {
                this.raceTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> LapTime {
            get {
                return this.lapTimeField;
            }
            set {
                this.lapTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> Lap {
            get {
                return this.lapField;
            }
            set {
                this.lapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<short> LeaderLap {
            get {
                return this.leaderLapField;
            }
            set {
                this.leaderLapField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> FlagState {
            get {
                return this.flagStateField;
            }
            set {
                this.flagStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Invalid {
            get {
                return this.invalidField;
            }
            set {
                this.invalidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfSession SessionReference {
            get {
                return this.sessionReferenceField;
            }
            set {
                this.sessionReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfValidTag ValidTagReference {
            get {
                return this.validTagReferenceField;
            }
            set {
                this.validTagReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfSession : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfValidTag : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Session : EntityObject {
        
        private long sessionIDField;
        
        private int eventClassIDField;
        
        private System.Nullable<System.DateTime> startTimeField;
        
        private System.Nullable<System.DateTime> schedStopTimeField;
        
        private System.Nullable<int> schedLapsField;
        
        private System.Nullable<bool> rollingStartField;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        /// <remarks/>
        public long SessionID {
            get {
                return this.sessionIDField;
            }
            set {
                this.sessionIDField = value;
            }
        }
        
        /// <remarks/>
        public int EventClassID {
            get {
                return this.eventClassIDField;
            }
            set {
                this.eventClassIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartTime {
            get {
                return this.startTimeField;
            }
            set {
                this.startTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> SchedStopTime {
            get {
                return this.schedStopTimeField;
            }
            set {
                this.schedStopTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> SchedLaps {
            get {
                return this.schedLapsField;
            }
            set {
                this.schedLapsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> RollingStart {
            get {
                return this.rollingStartField;
            }
            set {
                this.rollingStartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EventClass : EntityObject {
        
        private long eventClassIDField;
        
        private long eventIDField;
        
        private long classIDField;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        private EntityReferenceOfRaceClass raceClassReferenceField;
        
        private EntityReferenceOfEvent eventReferenceField;
        
        /// <remarks/>
        public long EventClassID {
            get {
                return this.eventClassIDField;
            }
            set {
                this.eventClassIDField = value;
            }
        }
        
        /// <remarks/>
        public long EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        public long ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfRaceClass RaceClassReference {
            get {
                return this.raceClassReferenceField;
            }
            set {
                this.raceClassReferenceField = value;
            }
        }
        
        /// <remarks/>
        public EntityReferenceOfEvent EventReference {
            get {
                return this.eventReferenceField;
            }
            set {
                this.eventReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class EntityReferenceOfEvent : EntityReference {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RaceClass : EntityObject {
        
        private long classIDField;
        
        private string classNameField;
        
        private System.Nullable<byte> minAgeField;
        
        private System.Nullable<byte> maxAgeField;
        
        private string genderField;
        
        private string vehicleTypeField;
        
        private string vehicleModelField;
        
        private System.Nullable<int> vehicleCCField;
        
        private System.Nullable<bool> deletedField;
        
        private System.Nullable<System.DateTime> lastUpdatedField;
        
        /// <remarks/>
        public long ClassID {
            get {
                return this.classIDField;
            }
            set {
                this.classIDField = value;
            }
        }
        
        /// <remarks/>
        public string ClassName {
            get {
                return this.classNameField;
            }
            set {
                this.classNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> MinAge {
            get {
                return this.minAgeField;
            }
            set {
                this.minAgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<byte> MaxAge {
            get {
                return this.maxAgeField;
            }
            set {
                this.maxAgeField = value;
            }
        }
        
        /// <remarks/>
        public string Gender {
            get {
                return this.genderField;
            }
            set {
                this.genderField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleType {
            get {
                return this.vehicleTypeField;
            }
            set {
                this.vehicleTypeField = value;
            }
        }
        
        /// <remarks/>
        public string VehicleModel {
            get {
                return this.vehicleModelField;
            }
            set {
                this.vehicleModelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> VehicleCC {
            get {
                return this.vehicleCCField;
            }
            set {
                this.vehicleCCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Event : EntityObject {
        
        private long eventIDField;
        
        private string eventNameField;
        
        private string eventLocationField;
        
        private System.Nullable<System.DateTime> startDateField;
        
        private System.Nullable<System.DateTime> endDateField;
        
        private System.Nullable<bool> deletedField;
        
        private string lastUpdatedField;
        
        /// <remarks/>
        public long EventID {
            get {
                return this.eventIDField;
            }
            set {
                this.eventIDField = value;
            }
        }
        
        /// <remarks/>
        public string EventName {
            get {
                return this.eventNameField;
            }
            set {
                this.eventNameField = value;
            }
        }
        
        /// <remarks/>
        public string EventLocation {
            get {
                return this.eventLocationField;
            }
            set {
                this.eventLocationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> StartDate {
            get {
                return this.startDateField;
            }
            set {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> EndDate {
            get {
                return this.endDateField;
            }
            set {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<bool> Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
            }
        }
        
        /// <remarks/>
        public string LastUpdated {
            get {
                return this.lastUpdatedField;
            }
            set {
                this.lastUpdatedField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynchronizeCompetitorDataWithClientCompletedEventHandler(object sender, SynchronizeCompetitorDataWithClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynchronizeCompetitorDataWithClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynchronizeCompetitorDataWithClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public Competitor[] croutlist {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Competitor[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynchronizeEventsDataWithClientCompletedEventHandler(object sender, SynchronizeEventsDataWithClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynchronizeEventsDataWithClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynchronizeEventsDataWithClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynchronizeRaceClassesDataWithClientCompletedEventHandler(object sender, SynchronizeRaceClassesDataWithClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynchronizeRaceClassesDataWithClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynchronizeRaceClassesDataWithClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynchronizeEventClassesDataWithClientCompletedEventHandler(object sender, SynchronizeEventClassesDataWithClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynchronizeEventClassesDataWithClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynchronizeEventClassesDataWithClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynchronizeSessionsDataWithClientCompletedEventHandler(object sender, SynchronizeSessionsDataWithClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynchronizeSessionsDataWithClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynchronizeSessionsDataWithClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SynchronizePassingsDataWithClientCompletedEventHandler(object sender, SynchronizePassingsDataWithClientCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SynchronizePassingsDataWithClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SynchronizePassingsDataWithClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetCompetitorDataCompletedEventHandler(object sender, GetCompetitorDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetCompetitorDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetCompetitorDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Competitor[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Competitor[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLastPassingDataCompletedEventHandler(object sender, GetLastPassingDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastPassingDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastPassingDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Passing[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Passing[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591